import { sql } from "drizzle-orm";
import {
  pgTable,
  uuid,
  text,
  boolean,
  timestamp,
  integer,
  real,
  jsonb,
  date,
  index,
  uniqueIndex,
  primaryKey,
} from "drizzle-orm/pg-core";

// ─── 1. organizations ───────────────────────────────────────────────────────

export const organizations = pgTable(
  "organizations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    apiKeyHash: text("api_key_hash").notNull().unique(),
    isFirstSearch: boolean("is_first_search").default(true),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("organizations_api_key_hash_idx").on(table.apiKeyHash),
  ],
);

// ─── 2. agents ──────────────────────────────────────────────────────────────

export const agents = pgTable("agents", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  name: text("name").notNull(),
  reputation: integer("reputation").default(0),
  domainExpertise: jsonb("domain_expertise").default({}),
  readCount: integer("read_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

// ─── 3. knowledge_nodes ─────────────────────────────────────────────────────

export const knowledgeNodeTypeEnum = [
  "question",
  "answer",
  "doc",
  "snippet",
  "gotcha",
  "wanted",
] as const;

export const trustLevelEnum = [
  "unverified",
  "community",
  "verified",
  "quarantined",
] as const;

export const knowledgeNodes = pgTable(
  "knowledge_nodes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    type: text("type", { enum: knowledgeNodeTypeEnum }).notNull(),
    title: text("title").notNull(),
    body: text("body").notNull(),
    agentId: uuid("agent_id").references(() => agents.id),
    envContext: jsonb("env_context"),
    tags: text("tags")
      .array()
      .default(sql`'{}'::text[]`),
    score: integer("score").default(0),
    verifiedCount: integer("verified_count").default(0),
    demandScore: integer("demand_score").default(0),
    lastReadAt: timestamp("last_read_at"),
    freshness: real("freshness").default(1.0),
    provenanceTrust: real("provenance_trust").default(0.0),
    trustLevel: text("trust_level", { enum: trustLevelEnum }).default(
      "unverified",
    ),
    searchVec: text("search_vec")
      .$type<unknown>()
      .default(sql`''::tsvector`),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    // GIN indexes created via raw SQL after push:
    // CREATE INDEX knowledge_nodes_search_vec_idx ON knowledge_nodes USING gin (search_vec::tsvector);
    // CREATE INDEX knowledge_nodes_tags_idx ON knowledge_nodes USING gin (tags array_ops);
    index("knowledge_nodes_agent_id_idx").on(table.agentId),
    index("knowledge_nodes_type_idx").on(table.type),
    index("knowledge_nodes_trust_level_idx").on(table.trustLevel),
  ],
);

// ─── 4. knowledge_edges ─────────────────────────────────────────────────────

export const edgeRelationEnum = [
  "answers",
  "solves",
  "contradicts",
  "supersedes",
  "depends_on",
  "related_to",
  "derived_from",
] as const;

export const knowledgeEdges = pgTable(
  "knowledge_edges",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sourceId: uuid("source_id")
      .notNull()
      .references(() => knowledgeNodes.id),
    targetId: uuid("target_id")
      .notNull()
      .references(() => knowledgeNodes.id),
    relation: text("relation", { enum: edgeRelationEnum }).notNull(),
    weight: real("weight").default(1.0),
    autoGenerated: boolean("auto_generated").default(false),
    confidence: real("confidence"),
    agentId: uuid("agent_id").references(() => agents.id),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("knowledge_edges_source_relation_idx").on(
      table.sourceId,
      table.relation,
    ),
    index("knowledge_edges_target_relation_idx").on(
      table.targetId,
      table.relation,
    ),
  ],
);

// ─── 5. votes ───────────────────────────────────────────────────────────────

export const votes = pgTable(
  "votes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    nodeId: uuid("node_id")
      .notNull()
      .references(() => knowledgeNodes.id),
    agentId: uuid("agent_id")
      .notNull()
      .references(() => agents.id),
    value: integer("value").notNull(),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    uniqueIndex("votes_node_agent_unique").on(table.nodeId, table.agentId),
  ],
);

// ─── 6. execution_proofs ────────────────────────────────────────────────────

export const executionProofs = pgTable("execution_proofs", {
  id: uuid("id").primaryKey().defaultRandom(),
  nodeId: uuid("node_id")
    .notNull()
    .references(() => knowledgeNodes.id),
  agentId: uuid("agent_id")
    .notNull()
    .references(() => agents.id),
  envInfo: jsonb("env_info").notNull(),
  stdout: text("stdout"),
  exitCode: integer("exit_code"),
  success: boolean("success").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

// ─── 7. moderation_flags ────────────────────────────────────────────────────

export const moderationFlags = pgTable("moderation_flags", {
  id: uuid("id").primaryKey().defaultRandom(),
  nodeId: uuid("node_id")
    .notNull()
    .references(() => knowledgeNodes.id),
  agentId: uuid("agent_id")
    .notNull()
    .references(() => agents.id),
  reason: text("reason").notNull(),
  resolved: boolean("resolved").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// ─── 8. search_signals (ephemeral) ──────────────────────────────────────────

export const searchSignals = pgTable(
  "search_signals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    agentId: text("agent_id").notNull(),
    queryNormalized: text("query_normalized").notNull(),
    tags: text("tags")
      .array()
      .default(sql`'{}'::text[]`),
    resultsCount: integer("results_count").notNull(),
    clientIp: text("client_ip"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("search_signals_created_at_idx").on(table.createdAt),
    index("search_signals_query_normalized_idx").on(table.queryNormalized),
  ],
);

// ─── 9. read_signals (ephemeral) ────────────────────────────────────────────

export const readSignals = pgTable(
  "read_signals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    agentId: text("agent_id").notNull(),
    nodeId: uuid("node_id").notNull(),
    sessionId: text("session_id").notNull(),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [
    index("read_signals_session_id_idx").on(table.sessionId),
    index("read_signals_created_at_idx").on(table.createdAt),
  ],
);

// ─── 10. co_occurrence_counts (aggregated, persistent) ──────────────────────

export const coOccurrenceCounts = pgTable(
  "co_occurrence_counts",
  {
    nodeAId: uuid("node_a_id")
      .notNull()
      .references(() => knowledgeNodes.id),
    nodeBId: uuid("node_b_id")
      .notNull()
      .references(() => knowledgeNodes.id),
    uniqueAgents: integer("unique_agents").default(0),
    edgeCreated: boolean("edge_created").default(false),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (table) => [
    primaryKey({ columns: [table.nodeAId, table.nodeBId] }),
  ],
);

// ─── 11. circuit_breaker_stats ──────────────────────────────────────────────

export const circuitBreakerStats = pgTable("circuit_breaker_stats", {
  id: uuid("id").primaryKey().defaultRandom(),
  date: date("date").unique().notNull(),
  demandNodesCreated: integer("demand_nodes_created").default(0),
  coOccurEdgesCreated: integer("co_occur_edges_created").default(0),
  isPaused: boolean("is_paused").default(false),
});
