import { db } from "@/lib/db";
import { circuitBreakerStats } from "@/lib/db/schema";
import { sql, eq } from "drizzle-orm";

function todayDateStr(): string {
  return new Date().toISOString().slice(0, 10);
}

export async function checkCircuitBreaker(): Promise<{
  tripped: boolean;
  reason?: string;
}> {
  const today = todayDateStr();

  // Get today's stats
  const todayRows = await db
    .select()
    .from(circuitBreakerStats)
    .where(eq(circuitBreakerStats.date, today));

  const todayStats = todayRows[0];
  const todayTotal =
    (todayStats?.demandNodesCreated ?? 0) +
    (todayStats?.coOccurEdgesCreated ?? 0);

  // Check if manually paused
  if (todayStats?.isPaused) {
    return { tripped: true, reason: "Circuit breaker manually paused" };
  }

  // Get trailing 7-day average (excluding today)
  const trailingRows = await db.execute(sql`
    SELECT
      COALESCE(AVG(demand_nodes_created + co_occur_edges_created), 0) AS avg_daily
    FROM circuit_breaker_stats
    WHERE date < ${today}
      AND date >= (${today}::date - INTERVAL '7 days')
  `);

  const avgDaily = Number(trailingRows[0]?.avg_daily ?? 0);

  // If no historical data, don't trip
  if (avgDaily === 0) {
    return { tripped: false };
  }

  if (todayTotal > 2 * avgDaily) {
    return {
      tripped: true,
      reason: `Today's auto-generated count (${todayTotal}) exceeds 2x trailing 7-day average (${avgDaily.toFixed(1)})`,
    };
  }

  return { tripped: false };
}

export async function recordAutoGenerated(
  type: "demand_node" | "co_occur_edge",
  count: number,
): Promise<void> {
  const today = todayDateStr();
  const col =
    type === "demand_node"
      ? "demand_nodes_created"
      : "co_occur_edges_created";

  await db.execute(sql`
    INSERT INTO circuit_breaker_stats (id, date, ${sql.raw(col)})
    VALUES (gen_random_uuid(), ${today}, ${count})
    ON CONFLICT (date)
    DO UPDATE SET ${sql.raw(col)} = circuit_breaker_stats.${sql.raw(col)} + ${count}
  `);
}

export async function resetCircuitBreaker(): Promise<void> {
  const today = todayDateStr();
  await db.execute(sql`
    UPDATE circuit_breaker_stats
    SET is_paused = false
    WHERE date = ${today}
  `);
}
