import { sql } from "drizzle-orm";
import { readSignals, coOccurrenceCounts, knowledgeEdges } from "@/lib/db/schema";
import { recordAutoGenerated } from "@/lib/growth/circuit-breaker";
import type { EnricherJob } from "./demand-detection";

export const coOccurrence: EnricherJob = {
  name: "co-occurrence",

  async process(tx): Promise<{ processed: number; created: number }> {
    // 1. Read read_signals (batched)
    const signals = await tx
      .select()
      .from(readSignals)
      .limit(10000);

    if (signals.length === 0) {
      return { processed: 0, created: 0 };
    }

    // 2. Group by session_id
    const sessions = new Map<string, { nodeIds: Set<string>; agentId: string }[]>();
    const sessionReads = new Map<string, Array<{ nodeId: string; agentId: string }>>();

    for (const signal of signals) {
      let reads = sessionReads.get(signal.sessionId);
      if (!reads) {
        reads = [];
        sessionReads.set(signal.sessionId, reads);
      }
      reads.push({ nodeId: signal.nodeId, agentId: signal.agentId });
    }

    // 3. For each session with 2+ reads, extract pairs
    // Track (pairKey -> Set<agentId>) across all sessions
    const pairAgents = new Map<string, Set<string>>();

    for (const [_sessionId, reads] of sessionReads) {
      const uniqueNodeIds = [...new Set(reads.map((r) => r.nodeId))].slice(0, 20);
      if (uniqueNodeIds.length < 2) continue;

      // Collect agent IDs for this session
      const sessionAgentIds = new Set(reads.map((r) => r.agentId));

      // Generate all canonical pairs
      for (let i = 0; i < uniqueNodeIds.length; i++) {
        for (let j = i + 1; j < uniqueNodeIds.length; j++) {
          const [nodeA, nodeB] =
            uniqueNodeIds[i] < uniqueNodeIds[j]
              ? [uniqueNodeIds[i], uniqueNodeIds[j]]
              : [uniqueNodeIds[j], uniqueNodeIds[i]];

          const key = `${nodeA}:${nodeB}`;
          let agents = pairAgents.get(key);
          if (!agents) {
            agents = new Set();
            pairAgents.set(key, agents);
          }
          for (const agentId of sessionAgentIds) {
            agents.add(agentId);
          }
        }
      }
    }

    // 5. Filter pairs with >= 5 unique agents
    let created = 0;

    for (const [key, agentIds] of pairAgents) {
      if (agentIds.size < 5) continue;

      const [nodeAId, nodeBId] = key.split(":");

      // UPSERT co_occurrence_counts
      await tx.execute(sql`
        INSERT INTO co_occurrence_counts (node_a_id, node_b_id, unique_agents, updated_at)
        VALUES (${nodeAId}, ${nodeBId}, ${agentIds.size}, NOW())
        ON CONFLICT (node_a_id, node_b_id)
        DO UPDATE SET
          unique_agents = co_occurrence_counts.unique_agents + ${agentIds.size},
          updated_at = NOW()
      `);

      // Check if edge needs to be created
      const rows = await tx
        .select()
        .from(coOccurrenceCounts)
        .where(
          sql`${coOccurrenceCounts.nodeAId} = ${nodeAId} AND ${coOccurrenceCounts.nodeBId} = ${nodeBId}`,
        );

      const record = rows[0];
      if (record && record.uniqueAgents >= 5 && !record.edgeCreated) {
        const confidence = record.uniqueAgents / (record.uniqueAgents + 10);

        await tx.insert(knowledgeEdges).values({
          sourceId: nodeAId,
          targetId: nodeBId,
          relation: "related_to",
          autoGenerated: true,
          confidence,
        });

        await tx.execute(sql`
          UPDATE co_occurrence_counts
          SET edge_created = true
          WHERE node_a_id = ${nodeAId} AND node_b_id = ${nodeBId}
        `);

        created++;
      }
    }

    if (created > 0) {
      await recordAutoGenerated("co_occur_edge", created);
    }

    return { processed: signals.length, created };
  },
};
