import { sql } from "drizzle-orm";
import { searchSignals, knowledgeNodes } from "@/lib/db/schema";
import { recordAutoGenerated } from "@/lib/growth/circuit-breaker";

export interface EnricherJob {
  name: string;
  process(tx: any): Promise<{ processed: number; created: number }>;
}

export const demandDetection: EnricherJob = {
  name: "demand-detection",

  async process(tx): Promise<{ processed: number; created: number }> {
    // 1. Read search_signals (batched)
    const signals = await tx
      .select()
      .from(searchSignals)
      .limit(10000);

    if (signals.length === 0) {
      return { processed: 0, created: 0 };
    }

    // 2. Group by query_normalized
    const groups = new Map<
      string,
      { agentIds: Set<string>; allZeroResults: boolean; tags: Set<string> }
    >();

    for (const signal of signals) {
      const key = signal.queryNormalized;
      let group = groups.get(key);
      if (!group) {
        group = { agentIds: new Set(), allZeroResults: true, tags: new Set() };
        groups.set(key, group);
      }
      group.agentIds.add(signal.agentId);
      if (signal.resultsCount !== 0) {
        group.allZeroResults = false;
      }
      if (signal.tags) {
        for (const tag of signal.tags) {
          group.tags.add(tag);
        }
      }
    }

    // 3. Filter: >= 5 unique agents AND all results_count = 0
    let created = 0;

    for (const [queryNormalized, group] of groups) {
      if (group.agentIds.size < 5 || !group.allZeroResults) {
        continue;
      }

      // Check if demand node already exists
      const existing = await tx
        .select()
        .from(knowledgeNodes)
        .where(
          sql`${knowledgeNodes.type} = 'wanted' AND ${knowledgeNodes.title} = ${queryNormalized}`,
        );

      if (existing.length > 0) {
        // Increment demand_score
        await tx.execute(sql`
          UPDATE knowledge_nodes
          SET demand_score = demand_score + ${group.agentIds.size}
          WHERE id = ${existing[0].id}
        `);
      } else {
        // Create new demand node
        await tx.insert(knowledgeNodes).values({
          type: "wanted",
          title: queryNormalized,
          body: "",
          tags: Array.from(group.tags),
          demandScore: group.agentIds.size,
          trustLevel: "unverified",
        });
        created++;
      }
    }

    // Record with circuit breaker
    if (created > 0) {
      await recordAutoGenerated("demand_node", created);
    }

    return { processed: signals.length, created };
  },
};
