import { sql } from "drizzle-orm";
import { knowledgeNodes } from "@/lib/db/schema";
import { recordAutoGenerated } from "../circuit-breaker";
import type { EnricherJob } from "./demand-detection";

const MIN_REPORTS_THRESHOLD = 10;
const HIGH_SUCCESS_RATE = 0.65;
const LOW_SUCCESS_RATE = 0.35;
const NODE_SUCCESS_THRESHOLD = 5;
const NODE_HIGH_SUCCESS = 0.8;
const NODE_LOW_SUCCESS = 0.3;

export const outcomeMining: EnricherJob = {
  name: "outcome-mining",

  async process(tx): Promise<{ processed: number; created: number }> {
    // 1. Query outcome_reports grouped by (action_type, first domain tag)
    let rows: Array<{
      action_type: string;
      domain: string;
      total: number;
      successes: number;
      success_rate: number;
    }> = [];

    try {
      const result = await tx.execute(sql`
        SELECT
          action_type,
          domain_tags[1] AS domain,
          COUNT(*)::int AS total,
          COUNT(*) FILTER (WHERE success = true)::int AS successes,
          ROUND(COUNT(*) FILTER (WHERE success = true)::numeric / COUNT(*)::numeric, 2)::float AS success_rate
        FROM outcome_reports
        WHERE created_at > NOW() - INTERVAL '24 hours'
          AND array_length(domain_tags, 1) > 0
        GROUP BY action_type, domain_tags[1]
        HAVING COUNT(*) >= ${MIN_REPORTS_THRESHOLD}
      `);
      rows = Array.from(result as any) as typeof rows;
    } catch {
      return { processed: 0, created: 0 };
    }

    let processed = rows.length;
    let created = 0;

    // 2. Create pattern nodes for divergent success rates
    for (const row of rows) {
      if (row.success_rate >= HIGH_SUCCESS_RATE || row.success_rate <= LOW_SUCCESS_RATE) {
        const ratePercent = Math.round(row.success_rate * 100);
        const sentiment = row.success_rate >= HIGH_SUCCESS_RATE ? "high success" : "low success";
        const title = `Detected: ${row.action_type} in ${row.domain} — ${ratePercent}% ${sentiment} rate`;

        // Check if pattern already exists
        const existing = await tx
          .select({ id: knowledgeNodes.id })
          .from(knowledgeNodes)
          .where(sql`${knowledgeNodes.type} = 'pattern' AND ${knowledgeNodes.title} = ${title}`)
          .limit(1);

        if (existing.length === 0) {
          await tx.execute(sql`
            INSERT INTO knowledge_nodes (type, title, body, tags, trust_level, search_vec)
            VALUES (
              'pattern',
              ${title},
              ${'Auto-detected pattern from ' + row.total + ' outcome reports. Success rate: ' + ratePercent + '% (' + row.successes + '/' + row.total + ' agents succeeded). Action type: ' + row.action_type + ', domain: ' + row.domain + '.'},
              ${sql`ARRAY[${row.domain}, ${row.action_type}]::text[]`},
              'unverified',
              to_tsvector('english', ${title})
            )
          `);
          created++;
        }
      }
    }

    // 3. Node-linked success tracking: boost/flag nodes based on outcome success rates
    let nodeRows: Array<{ node_id: string; total: number; success_rate: number }> = [];
    try {
      const nodeResult = await tx.execute(sql`
        SELECT
          node_id,
          COUNT(*)::int AS total,
          ROUND(COUNT(*) FILTER (WHERE success = true)::numeric / COUNT(*)::numeric, 2)::float AS success_rate
        FROM outcome_reports
        WHERE node_id IS NOT NULL
          AND created_at > NOW() - INTERVAL '7 days'
        GROUP BY node_id
        HAVING COUNT(*) >= ${NODE_SUCCESS_THRESHOLD}
      `);
      nodeRows = Array.from(nodeResult as any) as typeof nodeRows;
    } catch {
      // outcome_reports may not have node_id data yet
    }

    for (const row of nodeRows) {
      if (row.success_rate >= NODE_HIGH_SUCCESS) {
        // Boost trust for high-success nodes
        await tx.execute(sql`
          UPDATE knowledge_nodes
          SET trust_level = CASE
            WHEN trust_level = 'unverified' THEN 'community'
            ELSE trust_level
          END,
          provenance_trust = LEAST(1.0, provenance_trust + 0.1)
          WHERE id = ${row.node_id}::uuid
        `);
      } else if (row.success_rate <= NODE_LOW_SUCCESS) {
        // Flag low-success nodes for review
        await tx.execute(sql`
          UPDATE knowledge_nodes
          SET freshness = GREATEST(0.0, freshness - 0.2)
          WHERE id = ${row.node_id}::uuid
        `);
      }
      processed++;
    }

    if (created > 0) {
      await recordAutoGenerated("outcome_pattern", created);
    }

    return { processed, created };
  },
};
