import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../../src/lib/db/schema', () => ({
  readSignals: { _: 'readSignals' },
  coOccurrenceCounts: {
    nodeAId: 'node_a_id',
    nodeBId: 'node_b_id',
  },
  knowledgeEdges: { _: 'knowledgeEdges' },
}));

vi.mock('drizzle-orm', () => ({
  sql: Object.assign(
    (strings: TemplateStringsArray, ...values: unknown[]) => ({ strings, values }),
    { raw: (s: string) => s }
  ),
}));

vi.mock('../../src/lib/growth/circuit-breaker', () => ({
  recordAutoGenerated: vi.fn().mockResolvedValue(undefined),
}));

import { coOccurrence } from '../../src/lib/growth/jobs/co-occurrence';
import { recordAutoGenerated } from '../../src/lib/growth/circuit-breaker';

function makeTx() {
  return {
    select: vi.fn(),
    insert: vi.fn(),
    execute: vi.fn().mockResolvedValue(undefined),
  };
}

function makeReadSignal(sessionId: string, nodeId: string, agentId: string) {
  return { sessionId, nodeId, agentId };
}

describe('coOccurrence', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('creates related_to edge at 5+ unique agents', async () => {
    const tx = makeTx();

    // 5 agents each reading nodeA and nodeB in the same session
    const signals = [
      makeReadSignal('s1', 'nodeA', 'agent-1'),
      makeReadSignal('s1', 'nodeB', 'agent-1'),
      makeReadSignal('s2', 'nodeA', 'agent-2'),
      makeReadSignal('s2', 'nodeB', 'agent-2'),
      makeReadSignal('s3', 'nodeA', 'agent-3'),
      makeReadSignal('s3', 'nodeB', 'agent-3'),
      makeReadSignal('s4', 'nodeA', 'agent-4'),
      makeReadSignal('s4', 'nodeB', 'agent-4'),
      makeReadSignal('s5', 'nodeA', 'agent-5'),
      makeReadSignal('s5', 'nodeB', 'agent-5'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    // After UPSERT, select from co_occurrence_counts returns record with uniqueAgents >= 5, edge not yet created
    tx.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue([{
          nodeAId: 'nodeA',
          nodeBId: 'nodeB',
          uniqueAgents: 5,
          edgeCreated: false,
        }]),
      }),
    });

    tx.insert.mockReturnValue({
      values: vi.fn().mockResolvedValue(undefined),
    });

    const result = await coOccurrence.process(tx);

    expect(result.created).toBe(1);
    expect(tx.insert).toHaveBeenCalled();
    expect(recordAutoGenerated).toHaveBeenCalledWith('co_occur_edge', 1);
  });

  it('k-anonymity: no edge at 4 agents', async () => {
    const tx = makeTx();

    const signals = [
      makeReadSignal('s1', 'nodeA', 'agent-1'),
      makeReadSignal('s1', 'nodeB', 'agent-1'),
      makeReadSignal('s2', 'nodeA', 'agent-2'),
      makeReadSignal('s2', 'nodeB', 'agent-2'),
      makeReadSignal('s3', 'nodeA', 'agent-3'),
      makeReadSignal('s3', 'nodeB', 'agent-3'),
      makeReadSignal('s4', 'nodeA', 'agent-4'),
      makeReadSignal('s4', 'nodeB', 'agent-4'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    const result = await coOccurrence.process(tx);

    expect(result.created).toBe(0);
    expect(tx.insert).not.toHaveBeenCalled();
    expect(recordAutoGenerated).not.toHaveBeenCalled();
  });

  it('canonical pair ordering (node A id < node B id)', async () => {
    const tx = makeTx();

    // nodeZ > nodeA alphabetically, but canonical order should be nodeA:nodeZ
    const signals = [
      makeReadSignal('s1', 'nodeZ', 'agent-1'),
      makeReadSignal('s1', 'nodeA', 'agent-1'),
      makeReadSignal('s2', 'nodeZ', 'agent-2'),
      makeReadSignal('s2', 'nodeA', 'agent-2'),
      makeReadSignal('s3', 'nodeZ', 'agent-3'),
      makeReadSignal('s3', 'nodeA', 'agent-3'),
      makeReadSignal('s4', 'nodeZ', 'agent-4'),
      makeReadSignal('s4', 'nodeA', 'agent-4'),
      makeReadSignal('s5', 'nodeZ', 'agent-5'),
      makeReadSignal('s5', 'nodeA', 'agent-5'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    tx.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue([{
          nodeAId: 'nodeA',
          nodeBId: 'nodeZ',
          uniqueAgents: 5,
          edgeCreated: false,
        }]),
      }),
    });

    const valuesFn = vi.fn().mockResolvedValue(undefined);
    tx.insert.mockReturnValue({ values: valuesFn });

    await coOccurrence.process(tx);

    // The insert should use nodeA as sourceId and nodeZ as targetId (canonical order)
    expect(valuesFn).toHaveBeenCalledWith(
      expect.objectContaining({
        sourceId: 'nodeA',
        targetId: 'nodeZ',
        relation: 'related_to',
      }),
    );
  });

  it('confidence formula correct: uniqueAgents / (uniqueAgents + 10)', async () => {
    const tx = makeTx();

    const signals = [
      makeReadSignal('s1', 'nodeA', 'agent-1'),
      makeReadSignal('s1', 'nodeB', 'agent-1'),
      makeReadSignal('s2', 'nodeA', 'agent-2'),
      makeReadSignal('s2', 'nodeB', 'agent-2'),
      makeReadSignal('s3', 'nodeA', 'agent-3'),
      makeReadSignal('s3', 'nodeB', 'agent-3'),
      makeReadSignal('s4', 'nodeA', 'agent-4'),
      makeReadSignal('s4', 'nodeB', 'agent-4'),
      makeReadSignal('s5', 'nodeA', 'agent-5'),
      makeReadSignal('s5', 'nodeB', 'agent-5'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    const uniqueAgents = 15;
    tx.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue([{
          nodeAId: 'nodeA',
          nodeBId: 'nodeB',
          uniqueAgents,
          edgeCreated: false,
        }]),
      }),
    });

    const valuesFn = vi.fn().mockResolvedValue(undefined);
    tx.insert.mockReturnValue({ values: valuesFn });

    await coOccurrence.process(tx);

    const expectedConfidence = uniqueAgents / (uniqueAgents + 10); // 15/25 = 0.6
    expect(valuesFn).toHaveBeenCalledWith(
      expect.objectContaining({
        confidence: expectedConfidence,
      }),
    );
  });

  it('session windowing works (groups by session_id)', async () => {
    const tx = makeTx();

    // Two different sessions, each with different node pairs
    const signals = [
      makeReadSignal('session-A', 'node1', 'agent-1'),
      makeReadSignal('session-A', 'node2', 'agent-1'),
      makeReadSignal('session-B', 'node3', 'agent-2'),
      makeReadSignal('session-B', 'node4', 'agent-2'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    const result = await coOccurrence.process(tx);

    // Only 1 agent per pair, so no edges created (need 5)
    expect(result.created).toBe(0);
    expect(result.processed).toBe(4);
  });

  it('handles single-node sessions (no pairs generated)', async () => {
    const tx = makeTx();

    // Each session has only one node
    const signals = [
      makeReadSignal('s1', 'nodeA', 'agent-1'),
      makeReadSignal('s2', 'nodeB', 'agent-2'),
      makeReadSignal('s3', 'nodeC', 'agent-3'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    const result = await coOccurrence.process(tx);

    expect(result.created).toBe(0);
    expect(result.processed).toBe(3);
    // No UPSERT execute calls since no pairs
    expect(tx.execute).not.toHaveBeenCalled();
  });

  it('caps nodes per session to 20', async () => {
    const tx = makeTx();

    // Create a session with 25 unique nodes
    const signals: ReturnType<typeof makeReadSignal>[] = [];
    for (let i = 0; i < 25; i++) {
      signals.push(makeReadSignal('s1', `node-${String(i).padStart(3, '0')}`, 'agent-1'));
    }

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    // With 20 nodes capped, pairs = C(20,2) = 190
    // With only 1 agent, no edges created, but we can count execute calls
    const result = await coOccurrence.process(tx);

    // All 25 signals processed but only 20 nodes used for pairing
    // Since only 1 agent, no pairs meet the 5-agent threshold
    expect(result.created).toBe(0);
    expect(result.processed).toBe(25);
    // No execute calls since no pair has 5 agents
    expect(tx.execute).not.toHaveBeenCalled();
  });

  it('handles empty signal batch', async () => {
    const tx = makeTx();

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue([]),
      }),
    });

    const result = await coOccurrence.process(tx);
    expect(result).toEqual({ processed: 0, created: 0 });
  });
});
