import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../../src/lib/db/schema', () => ({
  searchSignals: { _: 'searchSignals' },
  knowledgeNodes: {
    type: 'type',
    title: 'title',
  },
}));

vi.mock('drizzle-orm', () => ({
  sql: Object.assign(
    (strings: TemplateStringsArray, ...values: unknown[]) => ({ strings, values }),
    { raw: (s: string) => s }
  ),
}));

vi.mock('../../src/lib/growth/circuit-breaker', () => ({
  recordAutoGenerated: vi.fn().mockResolvedValue(undefined),
}));

import { demandDetection } from '../../src/lib/growth/jobs/demand-detection';
import { recordAutoGenerated } from '../../src/lib/growth/circuit-breaker';

function makeTx() {
  return {
    select: vi.fn(),
    insert: vi.fn(),
    execute: vi.fn().mockResolvedValue(undefined),
  };
}

function makeSignal(queryNormalized: string, agentId: string, resultsCount = 0, tags: string[] = []) {
  return { queryNormalized, agentId, resultsCount, tags };
}

describe('demandDetection', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('creates WANTED node at exactly 5 unique agents', async () => {
    const tx = makeTx();

    const signals = [
      makeSignal('python stripe', 'agent-1'),
      makeSignal('python stripe', 'agent-2'),
      makeSignal('python stripe', 'agent-3'),
      makeSignal('python stripe', 'agent-4'),
      makeSignal('python stripe', 'agent-5'),
    ];

    // select().from(searchSignals).limit() -> signals
    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    // select().from(knowledgeNodes).where() -> no existing node
    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue([]),
      }),
    });

    // insert().values() -> create new node
    tx.insert.mockReturnValue({
      values: vi.fn().mockResolvedValue(undefined),
    });

    const result = await demandDetection.process(tx);

    expect(result.created).toBe(1);
    expect(result.processed).toBe(5);
    expect(tx.insert).toHaveBeenCalled();
    expect(recordAutoGenerated).toHaveBeenCalledWith('demand_node', 1);
  });

  it('does NOT create WANTED node at 4 agents (below threshold)', async () => {
    const tx = makeTx();

    const signals = [
      makeSignal('python stripe', 'agent-1'),
      makeSignal('python stripe', 'agent-2'),
      makeSignal('python stripe', 'agent-3'),
      makeSignal('python stripe', 'agent-4'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    const result = await demandDetection.process(tx);

    expect(result.created).toBe(0);
    expect(result.processed).toBe(4);
    expect(tx.insert).not.toHaveBeenCalled();
    expect(recordAutoGenerated).not.toHaveBeenCalled();
  });

  it('increments demand_score for existing WANTED node', async () => {
    const tx = makeTx();

    const signals = [
      makeSignal('python stripe', 'agent-1'),
      makeSignal('python stripe', 'agent-2'),
      makeSignal('python stripe', 'agent-3'),
      makeSignal('python stripe', 'agent-4'),
      makeSignal('python stripe', 'agent-5'),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    // Existing node found
    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue([{ id: 'existing-node-id', type: 'wanted' }]),
      }),
    });

    const result = await demandDetection.process(tx);

    expect(result.created).toBe(0);
    expect(result.processed).toBe(5);
    expect(tx.execute).toHaveBeenCalled(); // UPDATE demand_score
    expect(tx.insert).not.toHaveBeenCalled();
    expect(recordAutoGenerated).not.toHaveBeenCalled();
  });

  it('handles empty signal batch (returns processed: 0, created: 0)', async () => {
    const tx = makeTx();

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue([]),
      }),
    });

    const result = await demandDetection.process(tx);

    expect(result).toEqual({ processed: 0, created: 0 });
  });

  it('does not create WANTED node when some signals have non-zero results_count', async () => {
    const tx = makeTx();

    const signals = [
      makeSignal('python stripe', 'agent-1', 0),
      makeSignal('python stripe', 'agent-2', 0),
      makeSignal('python stripe', 'agent-3', 0),
      makeSignal('python stripe', 'agent-4', 0),
      makeSignal('python stripe', 'agent-5', 3), // non-zero
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    const result = await demandDetection.process(tx);

    expect(result.created).toBe(0);
    expect(tx.insert).not.toHaveBeenCalled();
  });

  it('respects LIMIT 10000 batch cap (limit is called with 10000)', async () => {
    const tx = makeTx();

    const limitFn = vi.fn().mockResolvedValue([]);
    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: limitFn,
      }),
    });

    await demandDetection.process(tx);

    expect(limitFn).toHaveBeenCalledWith(10000);
  });

  it('collects tags from all signals into the new WANTED node', async () => {
    const tx = makeTx();

    const signals = [
      makeSignal('python stripe', 'agent-1', 0, ['python']),
      makeSignal('python stripe', 'agent-2', 0, ['stripe']),
      makeSignal('python stripe', 'agent-3', 0, ['python', 'payments']),
      makeSignal('python stripe', 'agent-4', 0, []),
      makeSignal('python stripe', 'agent-5', 0, ['stripe']),
    ];

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(signals),
      }),
    });

    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue([]),
      }),
    });

    const valuesFn = vi.fn().mockResolvedValue(undefined);
    tx.insert.mockReturnValue({ values: valuesFn });

    await demandDetection.process(tx);

    expect(valuesFn).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'wanted',
        title: 'python stripe',
        tags: expect.arrayContaining(['python', 'stripe', 'payments']),
      }),
    );
  });
});
