import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

// Mock db module
vi.mock('../../src/lib/db', () => ({
  db: {
    execute: vi.fn(),
    transaction: vi.fn(),
  },
}));

vi.mock('../../src/lib/db/schema', () => ({
  searchSignals: { _: 'searchSignals' },
  readSignals: { _: 'readSignals' },
}));

vi.mock('drizzle-orm', () => ({
  sql: Object.assign(
    (strings: TemplateStringsArray, ...values: unknown[]) => ({ strings, values }),
    { raw: (s: string) => s }
  ),
}));

// Mock circuit breaker
vi.mock('../../src/lib/growth/circuit-breaker', () => ({
  checkCircuitBreaker: vi.fn(),
  recordAutoGenerated: vi.fn().mockResolvedValue(undefined),
}));

// Mock all jobs
vi.mock('../../src/lib/growth/jobs/demand-detection', () => ({
  demandDetection: {
    name: 'demand-detection',
    process: vi.fn().mockResolvedValue({ processed: 0, created: 0 }),
  },
}));

vi.mock('../../src/lib/growth/jobs/co-occurrence', () => ({
  coOccurrence: {
    name: 'co-occurrence',
    process: vi.fn().mockResolvedValue({ processed: 0, created: 0 }),
  },
}));

vi.mock('../../src/lib/growth/jobs/freshness', () => ({
  freshness: {
    name: 'freshness',
    process: vi.fn().mockResolvedValue({ processed: 0, created: 0 }),
  },
}));

vi.mock('../../src/lib/growth/jobs/trust-cascade', () => ({
  trustCascade: {
    name: 'trust-cascade',
    process: vi.fn().mockResolvedValue({ processed: 0, created: 0 }),
  },
}));

vi.mock('../../src/lib/growth/jobs/domain-expertise', () => ({
  domainExpertise: {
    name: 'domain-expertise',
    process: vi.fn().mockResolvedValue({ processed: 0, created: 0 }),
  },
}));

import { db } from '../../src/lib/db';
import { checkCircuitBreaker } from '../../src/lib/growth/circuit-breaker';
import { runEnricherCycle } from '../../src/lib/growth/enricher';
import { demandDetection } from '../../src/lib/growth/jobs/demand-detection';
import { coOccurrence } from '../../src/lib/growth/jobs/co-occurrence';
import { freshness } from '../../src/lib/growth/jobs/freshness';
import { trustCascade } from '../../src/lib/growth/jobs/trust-cascade';
import { domainExpertise } from '../../src/lib/growth/jobs/domain-expertise';

describe('runEnricherCycle', () => {
  let consoleSpy: ReturnType<typeof vi.spyOn>;
  const originalEnv = { ...process.env };

  beforeEach(() => {
    vi.clearAllMocks();
    consoleSpy = vi.spyOn(console, 'log').mockImplementation(() => {});

    // Reset env vars
    delete process.env.ENABLE_DEMAND_DETECTION;
    delete process.env.ENABLE_CO_OCCURRENCE;
    delete process.env.ENABLE_FRESHNESS;
    delete process.env.ENABLE_TRUST_CASCADE;
    delete process.env.ENABLE_DOMAIN_EXPERTISE;
  });

  afterEach(() => {
    consoleSpy.mockRestore();
    process.env = { ...originalEnv };
  });

  it('skips cycle when advisory lock is held', async () => {
    // Lock not acquired
    (db.execute as ReturnType<typeof vi.fn>).mockResolvedValueOnce([{ acquired: false }]);

    await runEnricherCycle();

    expect(consoleSpy).toHaveBeenCalledWith(
      expect.stringContaining('already running'),
    );
    // Should not check circuit breaker
    expect(checkCircuitBreaker).not.toHaveBeenCalled();
  });

  it('checks circuit breaker first, skips all jobs when tripped', async () => {
    // Lock acquired
    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])   // pg_try_advisory_lock
      .mockResolvedValueOnce(undefined);               // pg_advisory_unlock

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockResolvedValue({
      tripped: true,
      reason: 'Too many auto-generated items',
    });

    await runEnricherCycle();

    expect(checkCircuitBreaker).toHaveBeenCalled();
    // No transaction should be started
    expect(db.transaction).not.toHaveBeenCalled();
    // Jobs should not be called
    expect(demandDetection.process).not.toHaveBeenCalled();
  });

  it('respects feature flags (skips disabled jobs)', async () => {
    // Disable demand detection and co-occurrence
    process.env.ENABLE_DEMAND_DETECTION = 'false';
    process.env.ENABLE_CO_OCCURRENCE = 'false';

    // Lock acquired
    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])
      .mockResolvedValueOnce(undefined); // unlock

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockResolvedValue({ tripped: false });

    // Transaction mock that executes the callback
    (db.transaction as ReturnType<typeof vi.fn>).mockImplementation(async (cb: (tx: any) => Promise<void>) => {
      const fakeTx = {
        execute: vi.fn().mockResolvedValue([{ cnt: 0 }]),
      };
      await cb(fakeTx);
    });

    await runEnricherCycle();

    // demand-detection and co-occurrence should NOT be called
    expect(demandDetection.process).not.toHaveBeenCalled();
    expect(coOccurrence.process).not.toHaveBeenCalled();

    // freshness, trust-cascade, domain-expertise should be called
    expect(freshness.process).toHaveBeenCalled();
    expect(trustCascade.process).toHaveBeenCalled();
    expect(domainExpertise.process).toHaveBeenCalled();
  });

  it('releases advisory lock in finally block', async () => {
    // Lock acquired
    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])
      .mockResolvedValueOnce(undefined); // unlock

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockRejectedValue(
      new Error('Circuit breaker DB error'),
    );

    await expect(runEnricherCycle()).rejects.toThrow('Circuit breaker DB error');

    // Advisory lock should still be released (2nd execute call)
    expect(db.execute).toHaveBeenCalledTimes(2);
  });

  it('releases advisory lock even when transaction fails', async () => {
    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])
      .mockResolvedValueOnce(undefined); // unlock

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockResolvedValue({ tripped: false });

    (db.transaction as ReturnType<typeof vi.fn>).mockRejectedValue(
      new Error('Transaction failed'),
    );

    await expect(runEnricherCycle()).rejects.toThrow('Transaction failed');

    // Lock should still be released
    expect(db.execute).toHaveBeenCalledTimes(2);
  });

  it('structured JSON log includes all expected fields', async () => {
    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])
      .mockResolvedValueOnce(undefined); // unlock

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockResolvedValue({ tripped: false });

    (db.transaction as ReturnType<typeof vi.fn>).mockImplementation(async (cb: (tx: any) => Promise<void>) => {
      const fakeTx = {
        execute: vi.fn().mockResolvedValue([{ cnt: 0 }]),
      };
      await cb(fakeTx);
    });

    await runEnricherCycle();

    // Find the structured log call (JSON.stringify output)
    const jsonLogCall = consoleSpy.mock.calls.find((call) => {
      try {
        const parsed = JSON.parse(call[0]);
        return parsed.event === 'enricher_cycle';
      } catch {
        return false;
      }
    });

    expect(jsonLogCall).toBeDefined();
    const logData = JSON.parse(jsonLogCall![0]);

    expect(logData).toHaveProperty('event', 'enricher_cycle');
    expect(logData).toHaveProperty('duration_ms');
    expect(typeof logData.duration_ms).toBe('number');
    expect(logData).toHaveProperty('circuit_breaker', 'open');
    expect(logData).toHaveProperty('jobs_run');
    expect(logData).toHaveProperty('jobs_skipped');
    expect(logData).toHaveProperty('signals_swept');
    expect(Array.isArray(logData.jobs_run)).toBe(true);
    expect(Array.isArray(logData.jobs_skipped)).toBe(true);
  });

  it('logs circuit_breaker as "paused" when breaker is tripped', async () => {
    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])
      .mockResolvedValueOnce(undefined);

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockResolvedValue({ tripped: true });

    await runEnricherCycle();

    const jsonLogCall = consoleSpy.mock.calls.find((call) => {
      try {
        const parsed = JSON.parse(call[0]);
        return parsed.event === 'enricher_cycle';
      } catch {
        return false;
      }
    });

    expect(jsonLogCall).toBeDefined();
    const logData = JSON.parse(jsonLogCall![0]);
    expect(logData.circuit_breaker).toBe('paused');
    expect(logData.jobs_run).toEqual([]);
  });

  it('defaults to enabled when env var is not set', async () => {
    // No env vars set - all jobs should be enabled by default

    (db.execute as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce([{ acquired: true }])
      .mockResolvedValueOnce(undefined);

    (checkCircuitBreaker as ReturnType<typeof vi.fn>).mockResolvedValue({ tripped: false });

    (db.transaction as ReturnType<typeof vi.fn>).mockImplementation(async (cb: (tx: any) => Promise<void>) => {
      const fakeTx = {
        execute: vi.fn().mockResolvedValue([{ cnt: 0 }]),
      };
      await cb(fakeTx);
    });

    await runEnricherCycle();

    expect(demandDetection.process).toHaveBeenCalled();
    expect(coOccurrence.process).toHaveBeenCalled();
    expect(freshness.process).toHaveBeenCalled();
    expect(trustCascade.process).toHaveBeenCalled();
    expect(domainExpertise.process).toHaveBeenCalled();
  });
});
