import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../../src/lib/db/schema", () => ({
  knowledgeNodes: {
    id: "id",
    type: "type",
    title: "title",
  },
}));

vi.mock("drizzle-orm", () => ({
  sql: Object.assign(
    (strings: TemplateStringsArray, ...values: unknown[]) => ({ strings, values }),
    { raw: (s: string) => s },
  ),
}));

vi.mock("../../src/lib/growth/circuit-breaker", () => ({
  recordAutoGenerated: vi.fn().mockResolvedValue(undefined),
}));

import { outcomeMining } from "../../src/lib/growth/jobs/outcome-mining";
import { recordAutoGenerated } from "../../src/lib/growth/circuit-breaker";

function makeTx() {
  return {
    select: vi.fn(),
    insert: vi.fn(),
    execute: vi.fn().mockResolvedValue([]),
  };
}

describe("outcomeMining", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns {processed: 0, created: 0} when no outcome reports exist", async () => {
    const tx = makeTx();

    // First execute: grouped outcome reports query returns empty
    tx.execute.mockResolvedValueOnce([]);

    const result = await outcomeMining.process(tx);

    expect(result).toEqual({ processed: 0, created: 0 });
  });

  it("creates pattern node when 10+ reports with divergent success rate exist", async () => {
    const tx = makeTx();

    // First execute: grouped outcome reports with high success rate
    tx.execute.mockResolvedValueOnce([
      {
        action_type: "code_generation",
        domain: "typescript",
        total: 15,
        successes: 12,
        success_rate: 0.8,
      },
    ]);

    // select().from().where().limit() -> no existing pattern
    tx.select.mockReturnValueOnce({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          limit: vi.fn().mockResolvedValue([]),
        }),
      }),
    });

    // Second execute: insert the pattern node
    tx.execute.mockResolvedValueOnce(undefined);

    // Third execute: node-linked success tracking query returns empty
    tx.execute.mockResolvedValueOnce([]);

    const result = await outcomeMining.process(tx);

    expect(result.created).toBe(1);
    expect(result.processed).toBeGreaterThanOrEqual(1);
    expect(recordAutoGenerated).toHaveBeenCalledWith("outcome_pattern", 1);
  });

  it("does not create pattern when under threshold", async () => {
    const tx = makeTx();

    // First execute: reports with moderate success rate (between 0.35 and 0.65)
    tx.execute.mockResolvedValueOnce([
      {
        action_type: "code_generation",
        domain: "typescript",
        total: 12,
        successes: 6,
        success_rate: 0.5,
      },
    ]);

    // Second execute: node-linked success tracking returns empty
    tx.execute.mockResolvedValueOnce([]);

    const result = await outcomeMining.process(tx);

    expect(result.created).toBe(0);
    expect(result.processed).toBe(1);
    expect(recordAutoGenerated).not.toHaveBeenCalled();
  });

  it("handles gracefully when outcome_reports table doesn't exist (try/catch)", async () => {
    const tx = makeTx();

    // First execute: throws error (table doesn't exist)
    tx.execute.mockRejectedValueOnce(new Error("relation \"outcome_reports\" does not exist"));

    const result = await outcomeMining.process(tx);

    expect(result).toEqual({ processed: 0, created: 0 });
  });
});
